// Code generated by MockGen. DO NOT EDIT.
// Source: hasher.go
//
// Generated by this command:
//
//	mockgen -source=hasher.go -destination=../mocks/hasher.go -package=mocks -mock_names=Hasher=Hasher
//

// Package mocks is a generated GoMock package.
package mocks

import (
	logging "avito-shop/internal/logging"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// Hasher is a mock of Hasher interface.
type Hasher struct {
	ctrl     *gomock.Controller
	recorder *HasherMockRecorder
	isgomock struct{}
}

// HasherMockRecorder is the mock recorder for Hasher.
type HasherMockRecorder struct {
	mock *Hasher
}

// NewHasher creates a new mock instance.
func NewHasher(ctrl *gomock.Controller) *Hasher {
	mock := &Hasher{ctrl: ctrl}
	mock.recorder = &HasherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Hasher) EXPECT() *HasherMockRecorder {
	return m.recorder
}

// CompareHashAndPassword mocks base method.
func (m *Hasher) CompareHashAndPassword(hashedPassword, password []byte) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CompareHashAndPassword", hashedPassword, password)
	ret0, _ := ret[0].(error)
	return ret0
}

// CompareHashAndPassword indicates an expected call of CompareHashAndPassword.
func (mr *HasherMockRecorder) CompareHashAndPassword(hashedPassword, password any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CompareHashAndPassword", reflect.TypeOf((*Hasher)(nil).CompareHashAndPassword), hashedPassword, password)
}

// Hash mocks base method.
func (m *Hasher) Hash(data string, logger logging.Logger) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Hash", data, logger)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Hash indicates an expected call of Hash.
func (mr *HasherMockRecorder) Hash(data, logger any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Hash", reflect.TypeOf((*Hasher)(nil).Hash), data, logger)
}
