// Code generated by MockGen. DO NOT EDIT.
// Source: jwt.go
//
// Generated by this command:
//
//	mockgen -source=jwt.go -destination=../mocks/jwt.go -package=mocks -mock_names=TokenMaker=TokenMaker
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// TokenMaker is a mock of TokenMaker interface.
type TokenMaker struct {
	ctrl     *gomock.Controller
	recorder *TokenMakerMockRecorder
	isgomock struct{}
}

// TokenMakerMockRecorder is the mock recorder for TokenMaker.
type TokenMakerMockRecorder struct {
	mock *TokenMaker
}

// NewTokenMaker creates a new mock instance.
func NewTokenMaker(ctrl *gomock.Controller) *TokenMaker {
	mock := &TokenMaker{ctrl: ctrl}
	mock.recorder = &TokenMakerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *TokenMaker) EXPECT() *TokenMakerMockRecorder {
	return m.recorder
}

// CreateToken mocks base method.
func (m *TokenMaker) CreateToken(data any) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateToken", data)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateToken indicates an expected call of CreateToken.
func (mr *TokenMakerMockRecorder) CreateToken(data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateToken", reflect.TypeOf((*TokenMaker)(nil).CreateToken), data)
}

// GetPrefix mocks base method.
func (m *TokenMaker) GetPrefix() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrefix")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPrefix indicates an expected call of GetPrefix.
func (mr *TokenMakerMockRecorder) GetPrefix() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrefix", reflect.TypeOf((*TokenMaker)(nil).GetPrefix))
}

// ParseUserTokenRaw mocks base method.
func (m *TokenMaker) ParseUserTokenRaw(tokenString string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ParseUserTokenRaw", tokenString)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ParseUserTokenRaw indicates an expected call of ParseUserTokenRaw.
func (mr *TokenMakerMockRecorder) ParseUserTokenRaw(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ParseUserTokenRaw", reflect.TypeOf((*TokenMaker)(nil).ParseUserTokenRaw), tokenString)
}

// ValidateUserToken mocks base method.
func (m *TokenMaker) ValidateUserToken(tokenString string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserToken", tokenString)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUserToken indicates an expected call of ValidateUserToken.
func (mr *TokenMakerMockRecorder) ValidateUserToken(tokenString any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserToken", reflect.TypeOf((*TokenMaker)(nil).ValidateUserToken), tokenString)
}
