// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=../mocks/service_auth.go -package=mocks -mock_names=Auth=ServiceAuth
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "avito-shop/cmd/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// ServiceAuth is a mock of Auth interface.
type ServiceAuth struct {
	ctrl     *gomock.Controller
	recorder *ServiceAuthMockRecorder
	isgomock struct{}
}

// ServiceAuthMockRecorder is the mock recorder for ServiceAuth.
type ServiceAuthMockRecorder struct {
	mock *ServiceAuth
}

// NewServiceAuth creates a new mock instance.
func NewServiceAuth(ctrl *gomock.Controller) *ServiceAuth {
	mock := &ServiceAuth{ctrl: ctrl}
	mock.recorder = &ServiceAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ServiceAuth) EXPECT() *ServiceAuthMockRecorder {
	return m.recorder
}

// Auth mocks base method.
func (m *ServiceAuth) Auth(ctx context.Context, data dto.AuthRequest) (dto.AuthResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Auth", ctx, data)
	ret0, _ := ret[0].(dto.AuthResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Auth indicates an expected call of Auth.
func (mr *ServiceAuthMockRecorder) Auth(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Auth", reflect.TypeOf((*ServiceAuth)(nil).Auth), ctx, data)
}
