// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=../mocks/service_api.go -package=mocks -mock_names=API=ServiceAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	dto "avito-shop/cmd/dto"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// ServiceAPI is a mock of API interface.
type ServiceAPI struct {
	ctrl     *gomock.Controller
	recorder *ServiceAPIMockRecorder
	isgomock struct{}
}

// ServiceAPIMockRecorder is the mock recorder for ServiceAPI.
type ServiceAPIMockRecorder struct {
	mock *ServiceAPI
}

// NewServiceAPI creates a new mock instance.
func NewServiceAPI(ctrl *gomock.Controller) *ServiceAPI {
	mock := &ServiceAPI{ctrl: ctrl}
	mock.recorder = &ServiceAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *ServiceAPI) EXPECT() *ServiceAPIMockRecorder {
	return m.recorder
}

// BuyItem mocks base method.
func (m *ServiceAPI) BuyItem(ctx context.Context, itemID int, user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyItem", ctx, itemID, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuyItem indicates an expected call of BuyItem.
func (mr *ServiceAPIMockRecorder) BuyItem(ctx, itemID, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyItem", reflect.TypeOf((*ServiceAPI)(nil).BuyItem), ctx, itemID, user)
}

// GetUserInfo mocks base method.
func (m *ServiceAPI) GetUserInfo(ctx context.Context, username string) (*dto.InfoResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, username)
	ret0, _ := ret[0].(*dto.InfoResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *ServiceAPIMockRecorder) GetUserInfo(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*ServiceAPI)(nil).GetUserInfo), ctx, username)
}

// SendCoins mocks base method.
func (m *ServiceAPI) SendCoins(ctx context.Context, fromUser string, toUser dto.SendCoinRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCoins", ctx, fromUser, toUser)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCoins indicates an expected call of SendCoins.
func (mr *ServiceAPIMockRecorder) SendCoins(ctx, fromUser, toUser any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCoins", reflect.TypeOf((*ServiceAPI)(nil).SendCoins), ctx, fromUser, toUser)
}
