// Code generated by MockGen. DO NOT EDIT.
// Source: api.go
//
// Generated by this command:
//
//	mockgen -source=api.go -destination=../mocks/storage_api.go -package=mocks -mock_names=API=StorageAPI
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "avito-shop/internal/domain"
	views "avito-shop/internal/storage/views"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// StorageAPI is a mock of API interface.
type StorageAPI struct {
	ctrl     *gomock.Controller
	recorder *StorageAPIMockRecorder
	isgomock struct{}
}

// StorageAPIMockRecorder is the mock recorder for StorageAPI.
type StorageAPIMockRecorder struct {
	mock *StorageAPI
}

// NewStorageAPI creates a new mock instance.
func NewStorageAPI(ctrl *gomock.Controller) *StorageAPI {
	mock := &StorageAPI{ctrl: ctrl}
	mock.recorder = &StorageAPIMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StorageAPI) EXPECT() *StorageAPIMockRecorder {
	return m.recorder
}

// BuyItem mocks base method.
func (m *StorageAPI) BuyItem(ctx context.Context, itemID int, user string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BuyItem", ctx, itemID, user)
	ret0, _ := ret[0].(error)
	return ret0
}

// BuyItem indicates an expected call of BuyItem.
func (mr *StorageAPIMockRecorder) BuyItem(ctx, itemID, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BuyItem", reflect.TypeOf((*StorageAPI)(nil).BuyItem), ctx, itemID, user)
}

// GetUserInfo mocks base method.
func (m *StorageAPI) GetUserInfo(ctx context.Context, username string) (int, []views.UserInventory, []views.UserTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, username)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].([]views.UserInventory)
	ret2, _ := ret[2].([]views.UserTransaction)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *StorageAPIMockRecorder) GetUserInfo(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*StorageAPI)(nil).GetUserInfo), ctx, username)
}

// SendCoins mocks base method.
func (m *StorageAPI) SendCoins(ctx context.Context, fromUser string, transaction domain.SentTransaction) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCoins", ctx, fromUser, transaction)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCoins indicates an expected call of SendCoins.
func (mr *StorageAPIMockRecorder) SendCoins(ctx, fromUser, transaction any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCoins", reflect.TypeOf((*StorageAPI)(nil).SendCoins), ctx, fromUser, transaction)
}
