// Code generated by MockGen. DO NOT EDIT.
// Source: auth.go
//
// Generated by this command:
//
//	mockgen -source=auth.go -destination=../mocks/storage_auth.go -package=mocks -mock_names=Auth=StorageAuth
//

// Package mocks is a generated GoMock package.
package mocks

import (
	domain "avito-shop/internal/domain"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// StorageAuth is a mock of Auth interface.
type StorageAuth struct {
	ctrl     *gomock.Controller
	recorder *StorageAuthMockRecorder
	isgomock struct{}
}

// StorageAuthMockRecorder is the mock recorder for StorageAuth.
type StorageAuthMockRecorder struct {
	mock *StorageAuth
}

// NewStorageAuth creates a new mock instance.
func NewStorageAuth(ctrl *gomock.Controller) *StorageAuth {
	mock := &StorageAuth{ctrl: ctrl}
	mock.recorder = &StorageAuthMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *StorageAuth) EXPECT() *StorageAuthMockRecorder {
	return m.recorder
}

// CreateUser mocks base method.
func (m *StorageAuth) CreateUser(ctx context.Context, user domain.HashedUserData) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateUser", ctx, user)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateUser indicates an expected call of CreateUser.
func (mr *StorageAuthMockRecorder) CreateUser(ctx, user any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateUser", reflect.TypeOf((*StorageAuth)(nil).CreateUser), ctx, user)
}

// GetHashedUserPassword mocks base method.
func (m *StorageAuth) GetHashedUserPassword(ctx context.Context, username string) ([]byte, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHashedUserPassword", ctx, username)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHashedUserPassword indicates an expected call of GetHashedUserPassword.
func (mr *StorageAuthMockRecorder) GetHashedUserPassword(ctx, username any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHashedUserPassword", reflect.TypeOf((*StorageAuth)(nil).GetHashedUserPassword), ctx, username)
}
